/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AbcAppRouteImport } from './routes/abc/app'
import { Route as AbcAppDashboardRouteImport } from './routes/abc/app.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AbcAppRoute = AbcAppRouteImport.update({
  id: '/abc/app',
  path: '/abc/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AbcAppDashboardRoute = AbcAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AbcAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abc/app': typeof AbcAppRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/abc/app/dashboard': typeof AbcAppDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abc/app': typeof AbcAppRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/abc/app/dashboard': typeof AbcAppDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abc/app': typeof AbcAppRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/abc/app/dashboard': typeof AbcAppDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abc/app'
    | '/auth/signin'
    | '/auth/signup'
    | '/abc/app/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abc/app' | '/auth/signin' | '/auth/signup' | '/abc/app/dashboard'
  id:
    | '__root__'
    | '/'
    | '/abc/app'
    | '/auth/signin'
    | '/auth/signup'
    | '/abc/app/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbcAppRoute: typeof AbcAppRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abc/app': {
      id: '/abc/app'
      path: '/abc/app'
      fullPath: '/abc/app'
      preLoaderRoute: typeof AbcAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abc/app/dashboard': {
      id: '/abc/app/dashboard'
      path: '/dashboard'
      fullPath: '/abc/app/dashboard'
      preLoaderRoute: typeof AbcAppDashboardRouteImport
      parentRoute: typeof AbcAppRoute
    }
  }
}

interface AbcAppRouteChildren {
  AbcAppDashboardRoute: typeof AbcAppDashboardRoute
}

const AbcAppRouteChildren: AbcAppRouteChildren = {
  AbcAppDashboardRoute: AbcAppDashboardRoute,
}

const AbcAppRouteWithChildren =
  AbcAppRoute._addFileChildren(AbcAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbcAppRoute: AbcAppRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
