name: Zeros1 CI/CD Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ SSH into your server and deploy
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd Work-Permit   # 🔁 Replace with actual project path
            git reset --hard
            git clean -fd
            git pull origin main  # 📥 Pull latest code
            # PORT=${{secrets.PORT}} docker compose build  # 🐳 Build new images on the server
            # PORT=${{secrets.PORT}} docker compose up -d  # 🚀 Restart containers
            PORT=${{ secrets.PORT }} docker compose up -d --build
